### PR TITLE
loading-screen. Fix robot test for loading screen

### PR DESCRIPTION
**Pull request by andersnylund**
I were not sure if this is was a good way to fix the robot tests, so I made this PR to make sure

### CODE REVIEW

**Comment by andersnylund** [comment]
The problem was that previous `We display a question`-test was failing. If there is no choices returned or the fetch request fails, the app shows the loading screen infinitely. How is the runnig robot container sandboxed? Seems like the yarn application running inside the container is not able to get the choices from the API?

**Comment by VonLatvala** [comment]
It is not sandboxed at all, it _should_ have full internet connectivity, have you tried running the test locally according to the instructions provided in `README.md` (or even more accurately, running it as `Jenkinsfile` does it?)?

**Comment by andersnylund** [comment]
My bad, it was just the path that was wrong. Wondering what the `div[@class='jss21']` was in the xpath?

**Comment by VonLatvala** [comment]
> My bad, it was just the path that was wrong. Wondering what the `div[@class='jss21']` was in the xpath?

I made that change (to xpath) in a hurry, so just copypasted what XPath Helper gave me as I hovered the question. Don't really know, but your fix seems to be sane and correct.

**Pull request merged**
